In [1]:
#what is function transformer in machine learning?

In [3]:
# the function transformer is a tool in scikit_learn, a popular
# python library for machine learning,  that allows you to apply a
# specified fuction to the input data. the functiontransformer
# can be useful for  performing custom  transformer of  input
# data  in a machine  learninng pipeline.

In [8]:
from  sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1,2],[3,4]])

#define the transformer fuction
log_transform =FunctionTransformer(np.log1p)

#apply  the  transformer to the dataset
X_transformed =log_transform.transform(X)

# view the tranformed  data
print(X_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [14]:
# 1. custom feature Engineering

from  sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a  dataset
X=np.array([[1,2],[3,4]])

#define a custom feature engineering fuction 
def squ(X):
    return np.hstack((X,X**2))

#create a fuctiontransformer to  apply the  custom fuction
custom_transformer=FunctionTransformer(squ)

# apply the tranformer to  the input data
X_transformed=custom_transformer.transform(X)

# view thw transformed data
print(X_transformed)

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [18]:
from  sklearn.preprocessing import FunctionTransformer
import numpy as np

#create a dataset
X=np.array([[1,2],[3,4]])

# define  a  custom scalinng fuction
def  my_scaling(X):
    return  X/np.max(X)

# create a fuction transformer to  apply the custom fuction
custom_transformer = FunctionTransformer(my_scaling)

#apply the FuctionTransformer to  the input data
X_transformed=custom_transformer.transform(X)

# vies the transformed  data
print(X_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [20]:
from  sklearn.preprocessing import FunctionTransformer
import numpy as np

# create a dataset wwith  missing values
X=np.array([[1,2],[3,np.nan]])

# define a custom cleaning fuction
def my_cleaning(X):
    X[np.isnan(X)]=0
    return X

# create a fuction transformer to  apply the custom fuction
custom_transformer = FunctionTransformer(my_cleaning)

#apply the FuctionTransformer to  the input data
X_transformed=custom_transformer.transform(X)

# vies the transformed  data
print(X_transformed)

[[1. 2.]
 [3. 0.]]


In [21]:
import numpy as np
import pandas as pd

In [22]:
df=pd.read_csv("placement - placement.csv")

In [23]:
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [24]:
x=df.drop(columns=["placed"])
y=df["placed"]

In [26]:
from sklearn.preprocessing  import FunctionTransformer

In [29]:
log_transform=FunctionTransformer(np.log1p)

#apply  the  transformer to the dataset
X_transformed=log_transform.transform(x)


In [31]:
X_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [32]:
df=pd.read_csv("covid_toy - covid_toy.csv")

In [37]:
df.head(2)

age gender  fever cough     city has_covid
0   65   Male  103.0  Mild  Kolkata        No
1   32   Male  100.0  Mild    Delhi       Yes

In [38]:
x=df["age"]

In [36]:
def add(a):
    

age gender  fever cough     city has_covid
0   65   Male  103.0  Mild  Kolkata        No
1   32   Male  100.0  Mild    Delhi       Yes